[produce]
tomatoes|tomato
basil|basil leaves
garlic
garlic paste
onions|onion
red onion
jalapeño
lemon
lime juice
pineapple
spinach
spring onions
tenderstem broccoli

[dairy]
milk
cheese
yogurt
butter
parmesan|Parmesan cheese
cottage cheese
crumbled feta
sour cream

[pantry]
flour
sugar
pasta
rice
extra virgin olive oil|olive oil
chipotle-powder|chipotle powder
black pepper|ground black pepper
salt|sea salt
cannellini beans
black olives
chipotle hot sauce
chipotle paste
cooked mixed grains
cumin seeds
lasagne sheets
oregano
pickled red onions
roasted red peppers
smoked paprika
tahini

[meat]
chicken
beef
pork
chicken mince
free-range skinless chicken breasts

[seafood]
smoked salmon

[bakery]
bread
rolls
