name: CI

on:
  pull_request:
  push:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.ref }}
  cancel-in-progress: true

permissions: {}

jobs:
  ci:
    name: CI
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    permissions:
      contents: read

    steps:
      - name: Checkout Code
        uses: actions/checkout@v6

      - name: Set up mise
        uses: jdx/mise-action@v4

      - name: Validate Recipes
        run: mise check
